Faculty:418 Staff:418 Person:418 Linked:418:418 HasWord:79:418 Student:418 Department:418 ResearchProject:418 Course:418 
2
74:HasWord-id0
392:HasWord-id1,Faculty-id0,ResearchProject-id0,Linked-id1,Person-id0,Course-id0,Staff-id0,Student-id0,Department-id0,Linked-id0
Faculty:1,0 Staff:1,0 Person:1,0 Linked:1,0:1,0 HasWord:0,0:1,0 Student:1,0 Department:1,0 ResearchProject:1,0 Course:1,0 
64
0:!HasWord(w,p) v Course(p)
0:!HasWord(w,p) v Department(p)
0:!HasWord(w,p) v Person(p)
0:!HasWord(w,p) v Faculty(p)
0:!HasWord(w,p) v ResearchProject(p)
0:!HasWord(w,p) v Staff(p)
0:!HasWord(w,p) v Student(p)
0:!Course(x) v !Linked(x,y) v Course(y)
0:!Course(x) v !Linked(x,y) v Department(y)
0:!Course(x) v !Linked(x,y) v Person(y)
0:!Course(x) v !Linked(x,y) v Faculty(y)
0:!Course(x) v !Linked(x,y) v ResearchProject(y)
0:!Course(x) v !Linked(x,y) v Staff(y)
0:!Course(x) v !Linked(x,y) v Student(y)
0:!Department(x) v !Linked(x,y) v Course(y)
0:!Department(x) v !Linked(x,y) v Department(y)
0:!Department(x) v !Linked(x,y) v Person(y)
0:!Department(x) v !Linked(x,y) v Faculty(y)
0:!Department(x) v !Linked(x,y) v ResearchProject(y)
0:!Department(x) v !Linked(x,y) v Staff(y)
0:!Department(x) v !Linked(x,y) v Student(y)
0:!Person(x) v !Linked(x,y) v Course(y)
0:!Person(x) v !Linked(x,y) v Department(y)
0:!Person(x) v !Linked(x,y) v Person(y)
0:!Person(x) v !Linked(x,y) v Faculty(y)
0:!Person(x) v !Linked(x,y) v ResearchProject(y)
0:!Person(x) v !Linked(x,y) v Staff(y)
0:!Person(x) v !Linked(x,y) v Student(y)
0:!Faculty(x) v !Linked(x,y) v Course(y)
0:!Faculty(x) v !Linked(x,y) v Department(y)
0:!Faculty(x) v !Linked(x,y) v Person(y)
0:!Faculty(x) v !Linked(x,y) v Faculty(y)
0:!Faculty(x) v !Linked(x,y) v ResearchProject(y)
0:!Faculty(x) v !Linked(x,y) v Staff(y)
0:!Faculty(x) v !Linked(x,y) v Student(y)
0:!ResearchProject(x) v !Linked(x,y) v Course(y)
0:!ResearchProject(x) v !Linked(x,y) v Department(y)
0:!ResearchProject(x) v !Linked(x,y) v Person(y)
0:!ResearchProject(x) v !Linked(x,y) v Faculty(y)
0:!ResearchProject(x) v !Linked(x,y) v ResearchProject(y)
0:!ResearchProject(x) v !Linked(x,y) v Staff(y)
0:!ResearchProject(x) v !Linked(x,y) v Student(y)
0:!Staff(x) v !Linked(x,y) v Course(y)
0:!Staff(x) v !Linked(x,y) v Department(y)
0:!Staff(x) v !Linked(x,y) v Person(y)
0:!Staff(x) v !Linked(x,y) v Faculty(y)
0:!Staff(x) v !Linked(x,y) v ResearchProject(y)
0:!Staff(x) v !Linked(x,y) v Staff(y)
0:!Staff(x) v !Linked(x,y) v Student(y)
0:!Student(x) v !Linked(x,y) v Course(y)
0:!Student(x) v !Linked(x,y) v Department(y)
0:!Student(x) v !Linked(x,y) v Person(y)
0:!Student(x) v !Linked(x,y) v Faculty(y)
0:!Student(x) v !Linked(x,y) v ResearchProject(y)
0:!Student(x) v !Linked(x,y) v Staff(y)
0:!Student(x) v !Linked(x,y) v Student(y)
0:!Linked(x,y) v Linked(y,x)
0:!Course(p)
0:!Department(p)
0:!Person(p)
0:!Faculty(p)
0:!ResearchProject(p)
0:!Staff(p)
0:!Student(p)